### ISSUE TITLE
minified UMD detection

### ISSUE THREAD

**Issue by chengcyber** [guybedford/cjs-module-lexer#32]
## What

normally, this module should work with UMD bundle, since the umd wrapper function use `exports` identifier.

but after minified, the `exports` argument are mangled to single character.

I am not 100% sure this module should cover this case? but i am creating a similar functionality based on babel. I appreciate if i could use this module to replace mine.

example code:

```
!(function (t, e) {
  'object' == typeof exports && 'undefined' != typeof module
    ? e(
        exports,
      )
    : 'function' == typeof define && define.amd
    ? define([
        'exports',
      ], e)
    : e();
})(this, function (t, e) {
  'use strict';

  t.a = 'a';
  t.b = 'b';
});

```

expects detect `a`, `b`

**Comment by guybedford** [comment]
Because the detection of "exports" is entirely static, we won't even detect cases like:

```js
const e = exports;
e.name = 'value';
```

There is no execution tracing, because the performance requirements are first and foremost here not to slow down production loading scenarios.

If you load unminfied UMD that uses the `exports` name it will work:

```js
!(function (t, e) {
  'object' == typeof exports && 'undefined' != typeof module
    ? e(
        exports,
      )
    : 'function' == typeof define && define.amd
    ? define([
        'exports',
      ], e)
    : e();
})(this, function (exports, e) {
  'use strict';

  exports.a = 'a';
  exports.b = 'b';
});
```

will correctly detect the exports.

In cases where it doesn't work, we suggest writing a custom wrapper ES module to create the named exports yourself and then to load that module instead.

And when in doubt, just load the `default`.

Yes it is far from perfect, but it's something - hope that makes sense.

**Comment by guybedford** [comment]
If your own library is able to do deeper execution analysis I woudl suggest writing your own Babel plugin though that can handle more edge cases like these in a custom way.

These types of projects are fun anyway :)

**Comment by chengcyber** [comment]
Thanks for your quick reply and great work on pushing cjs, esm interop, totally understand the perf concern.
I would like to close this issue then.
